const mockObj = {"notes": 
                    [{ "id": "1", 
                        "name": "alala", 
                        "dateCreated": "30/02/2145", 
                        "category": "Task", 
                        "content": "some content", 
                        "dateEdited": "", 
                        "archived": false,
                    },    
                    {   "id": "2", 
                        "name": "The theory of evolution", 
                        "dateCreated": "11/12/2035", 
                        "category": "Idea", 
                        "content": "Implement newest", 
                        "dateEdited": "", 
                        "archived": false,
                    },
                    {   "id": "3", 
                        "name": "ewrewroewr", 
                        "dateCreated": "11/12/2035", 
                        "category": "Random Thought", 
                        "content": "ytpoytrypoweere,mmrerop", 
                        "dateEdited": "11/12/2035", 
                        "archived": false,
                    }],    
                 "showArchivedNotes": false,
                }
export { mockObj }